import { useMemo, useState } from 'react';
import { Card, EmptyState, Pill } from '../../components/ui';
import { shoppingRepository } from '../../repositories/shoppingRepository';
import { friendlyError } from '../../lib/errors';
import { money, normalize } from '../../services/shoppingIntelligence';
import { categoryIcon } from '../../lib/categoryIcon';

/** Converte texto de preço digitado (aceita vírgula decimal) em número; NaN se inválido. */
const parsePrice = (raw: string | undefined, fallback: number) => {
  if (raw === undefined || raw.trim() === '') return fallback;
  return Number(raw.replace(',', '.'));
};
import type { AppData, HistorySummary, ShoppingList } from '../../types/domain';

export function ShoppingMode({ userId, data, list, history, reload, notify, done }: { userId: string; data: AppData; list?: ShoppingList; history: HistorySummary[]; reload: () => Promise<void>; notify: (text: string) => void; done: () => void }) {
  const [marketPicker, setMarketPicker] = useState(false); const [prices, setPrices] = useState<Record<string, string>>({}); const [busy, setBusy] = useState('');
  const session = data.sessions.find(s => s.list_id === list?.id && s.status === 'active');
  const market = data.markets.find(m => m.id === session?.current_market_id);
  const items = data.items.filter(i => i.list_id === list?.id && i.status !== 'removed');
  const purchases = useMemo(() => data.purchases.filter(p => p.shopping_session_id === session?.id), [data.purchases, session?.id]);
  const purchasedIds = useMemo(() => new Set(purchases.map(p => p.shopping_list_item_id)), [purchases]);
  const total = purchases.reduce((sum, p) => sum + Number(p.total_price), 0);
  const projectedRemaining = useMemo(() => items.filter(i => !purchasedIds.has(i.id)).reduce((sum, item) => { const h = history.find(x => x.productId === item.product_id) || history.find(x => normalize(x.name) === normalize(item.name_snapshot)); return sum + Number(item.quantity) * Number(h?.average || item.estimated_price || 0); }, 0), [items, purchasedIds, history]);
  const chooseMarket = async (marketId: string) => { try { setBusy('market'); if (session) await shoppingRepository.changeSessionMarket(session.id, marketId); else if (list) await shoppingRepository.startSession(userId, list.id, marketId); await reload(); setMarketPicker(false); notify('Mercado atualizado para os próximos itens'); } catch (e) { notify(friendlyError(e)); } finally { setBusy(''); } };
  const toggle = async (itemId: string) => { if (!session || !market) return setMarketPicker(true); const purchase = purchases.find(p => p.shopping_list_item_id === itemId); try { setBusy(itemId); if (purchase) await shoppingRepository.undoPurchase(itemId, purchase.id); else { const item = items.find(i => i.id === itemId)!; const h = history.find(x => x.productId === item.product_id) || history.find(x => normalize(x.name) === normalize(item.name_snapshot)); const value = parsePrice(prices[item.id], Number(item.estimated_price || h?.average || 0)); if (!(value > 0)) { notify('Informe um preço válido antes de marcar o produto.'); return; } await shoppingRepository.purchaseItem(userId, session.id, item, market.id, value); } await reload(); } catch (e) { notify(friendlyError(e)); } finally { setBusy(''); } };
  const finish = async () => { if (!session || !purchases.length) return notify('Marque ao menos um produto comprado.'); try { setBusy('finish'); await shoppingRepository.finishSession(session.id, total); await reload(); notify('Compra finalizada e histórico atualizado'); done(); } catch (e) { notify(friendlyError(e)); } finally { setBusy(''); } };
  if (!list) return <EmptyState title="Selecione uma lista" description="Vá em “Listas”, escolha uma com itens pendentes e toque em “Comprar” para entrar no modo mercado."/>;
  return <div className="space-y-3"><Card className="sticky top-20 z-20 border-brand-200 dark:border-brand-500/30"><div className="flex items-center justify-between"><div><p className="text-xs text-slate-500 dark:text-slate-400">Comprando em</p><h2 className="text-xl font-bold">{market?.name || 'Selecione o mercado'}</h2></div><button onClick={() => setMarketPicker(true)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold dark:border-slate-600 dark:text-slate-200">{market ? 'Trocar mercado' : 'Escolher mercado'}</button></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-700"><div className="h-full bg-gradient-to-r from-brand-600 to-brand-500" style={{ width: `${items.length ? purchases.length / items.length * 100 : 0}%` }}/></div><div className="mt-2 flex justify-between text-xs text-slate-500 dark:text-slate-400"><span>{purchases.length}/{items.length} itens</span><span>{money(total)} gastos, {money(projectedRemaining)} restantes</span></div></Card>
    {items.map(item => { const purchase = purchases.find(p => p.shopping_list_item_id === item.id); const h = history.find(x => x.productId === item.product_id) || history.find(x => normalize(x.name) === normalize(item.name_snapshot)); const input = parsePrice(prices[item.id], Number(item.estimated_price || h?.average || 0)); const delta = h?.average && Number.isFinite(input) ? (input / h.average - 1) * 100 : 0; const purchaseMarket = data.markets.find(m => m.id === purchase?.market_id)?.name; const Icon = categoryIcon(data.categories.find(c => c.id === item.category_id)?.name); return <Card key={item.id} className={purchase ? 'opacity-75' : ''}><div className="flex gap-3"><button disabled={busy === item.id} onClick={() => void toggle(item.id)} className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl border text-lg font-bold ${purchase ? 'border-brand-600 bg-brand-600 text-white' : 'border-slate-300 dark:border-slate-600'}`}>{purchase ? '✓' : ''}</button><span className="mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-700 dark:bg-brand-500/15 dark:text-brand-300"><Icon size={16}/></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><strong>{item.quantity}x {item.name_snapshot}</strong><p className="text-xs text-slate-500 dark:text-slate-400">{purchaseMarket ? `Comprado em ${purchaseMarket}` : 'Pendente'}</p></div>{delta > 10 && !purchase && <Pill tone="danger">+{delta.toFixed(1)}%</Pill>}</div>{!purchase && <div className="mt-3 flex items-center gap-2"><label htmlFor={`price-${item.id}`} className="text-sm text-slate-500 dark:text-slate-400">Preço unit.</label><input id={`price-${item.id}`} inputMode="decimal" value={prices[item.id] ?? (item.estimated_price || h?.average || '')} onChange={e => setPrices(current => ({ ...current, [item.id]: e.target.value }))} className="w-32 rounded-xl border border-slate-200 bg-white px-3 py-2 text-right font-semibold dark:border-slate-600 dark:bg-slate-900" placeholder="0,00"/></div>}{h && <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">Média histórica {money(h.average)}, confiança {h.count >= 6 ? 'alta' : h.count >= 3 ? 'média' : 'baixa'} em {h.count} compra(s).</p>}</div></div></Card>; })}
    <button disabled={busy === 'finish'} onClick={() => void finish()} className="w-full rounded-2xl bg-brand-600 py-4 font-bold text-white">Finalizar compra, {money(total)}</button>
    {marketPicker && <div onClick={() => setMarketPicker(false)} className="fixed inset-0 z-50 flex items-end bg-slate-950/40 sm:items-center sm:justify-center"><div onClick={e => e.stopPropagation()} className="w-full rounded-t-3xl bg-white p-5 dark:bg-slate-800 sm:max-w-md sm:rounded-3xl"><h3 className="text-xl font-bold">Onde você está comprando?</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">A escolha vale para os próximos produtos. Itens já comprados mantêm o mercado original.</p><div className="mt-4 grid grid-cols-2 gap-2">{data.markets.map(m => <button disabled={busy === 'market'} key={m.id} onClick={() => void chooseMarket(m.id)} className={`rounded-2xl border p-4 text-left font-semibold ${market?.id === m.id ? 'border-brand-400 bg-brand-50 text-brand-700 dark:border-brand-500/50 dark:bg-brand-500/10 dark:text-brand-300' : 'border-slate-200 dark:border-slate-600'}`}>{m.name}</button>)}</div><button onClick={() => setMarketPicker(false)} className="mt-4 w-full rounded-2xl border border-slate-200 py-3 font-semibold dark:border-slate-600 dark:text-slate-200">Cancelar</button></div></div>}
  </div>;
}
