import { Card, EmptyState, Pill } from '../../components/ui';
import { compareMarkets, money } from '../../services/shoppingIntelligence';
import type { AppData, HistorySummary, ShoppingList } from '../../types/domain';

export function PricesPage({ data, history, list }: { data: AppData; history: HistorySummary[]; list?: ShoppingList }) {
  const items = data.items.filter(i => i.list_id === list?.id && i.status === 'pending'); const comparison = compareMarkets(items, history, data.markets);
  if (!history.length) return <EmptyState title="Sem histórico de preços" description="Finalize uma compra para começar a comparar mercados e acompanhar variações."/>;
  return <div className="space-y-4"><div><h2 className="text-2xl font-bold">Inteligência de preços</h2><p className="text-sm text-slate-500">Estimativas, nunca valores exatos, baseadas nas suas compras.</p></div><Card><h3 className="font-bold">Comparar compra, {list?.name || 'lista atual'}</h3><div className="mt-3 space-y-2">{comparison.length ? comparison.map((row, index) => <div key={row.market.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-3"><div><div className="flex gap-2"><strong>{row.market.name}</strong>{index === 0 && <Pill tone="success">melhor cobertura</Pill>}</div><p className="text-xs text-slate-500">{row.covered} de {row.itemCount} produtos com histórico</p></div><div className="text-right"><strong>{money(row.total)}</strong><p className="text-xs text-slate-500">estimados</p></div></div>) : <p className="text-sm text-slate-500">A lista ainda não possui itens com histórico por mercado.</p>}</div></Card><div className="grid gap-3 md:grid-cols-2">{history.sort((a, b) => b.count - a.count).map(item => { const markets = Object.entries(item.byMarket).sort((a, b) => a[1].average - b[1].average); return <Card key={item.productId || item.name}><div className="flex justify-between"><div><h3 className="font-bold">{item.name}</h3><p className="text-xs text-slate-500">{item.count} compra(s)</p></div><Pill tone={item.count >= 6 ? 'success' : item.count >= 3 ? 'warning' : 'neutral'}>confiança {item.count >= 6 ? 'alta' : item.count >= 3 ? 'média' : 'baixa'}</Pill></div><div className="mt-4 grid grid-cols-3 gap-2"><div><span className="text-xs text-slate-500">Último</span><strong className="block">{money(item.lastPrice)}</strong></div><div><span className="text-xs text-slate-500">Média</span><strong className="block">{money(item.average)}</strong></div><div><span className="text-xs text-slate-500">Menor</span><strong className="block">{money(item.minimum)}</strong></div></div>{markets.length > 0 && <div className="mt-4 border-t pt-3">{markets.map(([name, values]) => <div key={name} className="flex justify-between py-1 text-sm"><span>{name}</span><span>{money(values.average)} média</span></div>)}</div>}</Card>; })}</div></div>;
}

