import React, { useEffect, useMemo, useState } from 'react';
import { LocalMarket, LocalShoppingItem, LocalShoppingList, ShoppingLocalState, createLocalId, loadLocalShoppingState, resetLocalShoppingState, saveLocalShoppingState } from './services/localShoppingStore';

type View = 'inicio' | 'listas' | 'lista' | 'mercado' | 'precos' | 'resumo';
const money = (v:number) => v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const normalize = (v:string) => v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const daysBetween = (a:string,b=new Date().toISOString()) => Math.max(0,Math.round((new Date(b).getTime()-new Date(a).getTime())/86400000));

const rules = [
  {words:['arroz','feijao','cafe','acucar','sal','oleo','azeite','macarrao','farinha'],category:'Mercearia'},
  {words:['leite','queijo','iogurte','manteiga','requeijao'],category:'Laticínios'},
  {words:['carne','frango','peixe','linguica'],category:'Açougue'},
  {words:['banana','maca','laranja','tomate','alface','batata','cebola'],category:'Hortifruti'},
  {words:['pao','bolo','torrada'],category:'Padaria'},
  {words:['agua','suco','refrigerante','cerveja'],category:'Bebidas'},
  {words:['detergente','sabao','amaciante','desinfetante','multiuso'],category:'Limpeza'},
  {words:['papel higienico','sabonete','shampoo','creme dental','absorvente'],category:'Higiene'}
];

const categoryFor=(name:string,categories:string[])=>{
  const n=normalize(name); const found=rules.find(r=>r.words.some(w=>n.includes(w)))?.category;
  return found&&categories.includes(found)?found:(categories.includes('Outros')?'Outros':categories[0]||'Outros');
};
const parseItems=(text:string,categories:string[])=>text.split(/,|\n|;/).map(x=>x.trim()).filter(Boolean).map(part=>{
  const a=part.match(/^(\d+)\s*[xX]?\s+(.+)$/); const b=part.match(/^(.+?)\s+[xX](\d+)$/);
  const quantity=a?Number(a[1]):b?Number(b[2]):1; const name=(a?a[2]:b?b[1]:part).trim();
  return {name,quantity:Math.max(1,quantity),category:categoryFor(name,categories)};
});

const Card=({children,className=''}:{children:React.ReactNode;className?:string})=><div className={`rounded-3xl border border-slate-200 bg-white p-4 shadow-sm ${className}`}>{children}</div>;
const Pill=({children,tone='slate'}:{children:React.ReactNode;tone?:'slate'|'blue'|'green'|'amber'|'red'})=>{
  const tones={slate:'bg-slate-100 text-slate-600',blue:'bg-blue-50 text-blue-700',green:'bg-emerald-50 text-emerald-700',amber:'bg-amber-50 text-amber-700',red:'bg-red-50 text-red-700'};
  return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tones[tone]}`}>{children}</span>;
};

type Hist = {name:string;category:string;count:number;qty:number;prices:number[];dates:string[];markets:Map<string,number[]>};

export default function App(){
  const [state,setState]=useState<ShoppingLocalState>(()=>loadLocalShoppingState());
  const [view,setView]=useState<View>('inicio'); const [quick,setQuick]=useState(''); const [search,setSearch]=useState('');
  const [editing,setEditing]=useState<LocalShoppingItem|null>(null); const [notice,setNotice]=useState('');
  const [showList,setShowList]=useState(false); const [listName,setListName]=useState('');
  const [showMarket,setShowMarket]=useState(false); const [showSettings,setShowSettings]=useState(false);
  const [newCategory,setNewCategory]=useState(''); const [newMarket,setNewMarket]=useState(''); const [historyMode,setHistoryMode]=useState<'freq'|'recent'>('freq');

  useEffect(()=>saveLocalShoppingState(state),[state]);
  useEffect(()=>{if(!notice)return;const t=window.setTimeout(()=>setNotice(''),2600);return()=>window.clearTimeout(t)},[notice]);

  const list=useMemo(()=>state.lists.find(l=>l.id===state.activeListId)||state.lists[0],[state]); const items=list?.itens||[];
  const pending=items.filter(i=>i.status==='pendente'); const bought=items.filter(i=>i.status==='comprado');
  const actual=bought.reduce((s,i)=>s+(i.precoReal??i.precoEstimado)*i.quantidade,0);
  const projected=actual+pending.reduce((s,i)=>s+i.precoEstimado*i.quantidade,0); const progress=items.length?Math.round(bought.length/items.length*100):0;
  const updateList=(fn:(l:LocalShoppingList)=>LocalShoppingList)=>setState(s=>({...s,lists:s.lists.map(l=>l.id===s.activeListId?fn(l):l)}));

  const hist=useMemo(()=>{
    const map=new Map<string,Hist>();
    state.purchases.forEach(p=>p.itens.forEach(i=>{
      const key=normalize(i.nome);
      const cur:Hist=map.get(key)??{name:i.nome,category:i.categoria,count:0,qty:0,prices:[],dates:[],markets:new Map<string,number[]>()};
      cur.count++; cur.qty+=i.quantidade; cur.prices.push(i.precoUnitario); cur.dates.push(p.data);
      const m=i.mercado||p.mercado||'Não informado'; cur.markets.set(m,[...(cur.markets.get(m)||[]),i.precoUnitario]); map.set(key,cur);
    })); return map;
  },[state.purchases]);

  const suggestions=useMemo(()=>{
    const existing=new Set(items.map(i=>normalize(i.nome)));
    return [...hist.values()].filter(x=>!existing.has(normalize(x.name))).sort((a,b)=>historyMode==='freq'?b.count-a.count:new Date(b.dates[0]).getTime()-new Date(a.dates[0]).getTime()).slice(0,10);
  },[hist,items,historyMode]);

  const pantry=useMemo(()=>[...hist.values()].map(x=>{
    const dates=[...x.dates].sort((a,b)=>new Date(b).getTime()-new Date(a).getTime()); let avg=30;
    if(dates.length>1){const ints=dates.slice(0,-1).map((d,idx)=>daysBetween(d,dates[idx+1]));avg=Math.max(7,Math.round(ints.reduce((a,b)=>a+b,0)/ints.length));}
    const since=daysBetween(dates[0]); return {...x,avgInterval:avg,since,ratio:since/avg,avgQty:Math.max(1,Math.round(x.qty/x.count))};
  }).sort((a,b)=>b.ratio-a.ratio),[hist]);

  const addHistory=(x:Hist)=>{const price=x.prices.reduce((a,b)=>a+b,0)/x.prices.length;updateList(l=>({...l,atualizadaEm:new Date().toISOString(),itens:[...l.itens,{id:createLocalId('item'),nome:x.name,quantidade:Math.max(1,Math.round(x.qty/x.count)),categoria:x.category,precoEstimado:Number(price.toFixed(2)),status:'pendente',favorito:false,criadoEm:new Date().toISOString()}]}));setNotice(`${x.name} adicionado`)};
  const addQuick=()=>{const parsed=parseItems(quick,state.categories);if(!parsed.length)return;updateList(l=>{const next=l.itens.map(i=>({...i}));parsed.forEach(e=>{const old=next.find(i=>normalize(i.nome)===normalize(e.name)&&i.status==='pendente');const h=hist.get(normalize(e.name));const avg=h?.prices.length?h.prices.reduce((a,b)=>a+b,0)/h.prices.length:0;if(old)old.quantidade+=e.quantity;else next.push({id:createLocalId('item'),nome:e.name,quantidade:e.quantity,categoria:e.category,precoEstimado:Number(avg.toFixed(2)),status:'pendente',favorito:false,criadoEm:new Date().toISOString()})});return {...l,itens:next,atualizadaEm:new Date().toISOString()}});setQuick('');setNotice(`${parsed.length} item(ns) adicionado(s)`)};
  const toggle=(id:string)=>updateList(l=>({...l,itens:l.itens.map(i=>i.id===id?{...i,status:i.status==='pendente'?'comprado':'pendente',compradoEm:i.status==='pendente'?new Date().toISOString():undefined,mercadoCompra:i.status==='pendente'?(state.currentMarket||l.mercado):undefined}:i)}));
  const chooseMarket=(name:string)=>{setState(s=>({...s,currentMarket:name,marketMode:true,lists:s.lists.map(l=>l.id===s.activeListId?{...l,mercado:name}:l)}));setShowMarket(false);setView('mercado');setNotice(`Comprando em ${name}`)};
  const finish=()=>{if(!bought.length)return setNotice('Marque itens como comprados primeiro');const purchase={id:createLocalId('compra'),listaId:list.id,listaNome:list.nome,mercado:list.mercado,data:new Date().toISOString(),itens:bought.map(i=>{const unit=i.precoReal??i.precoEstimado;return{nome:i.nome,quantidade:i.quantidade,categoria:i.categoria,precoUnitario:unit,total:unit*i.quantidade,mercado:i.mercadoCompra||state.currentMarket||list.mercado,ean:i.ean}}),total:actual};setState(s=>({...s,marketMode:false,purchases:[purchase,...s.purchases],lists:s.lists.map(l=>l.id===s.activeListId?{...l,itens:l.itens.filter(i=>i.status!=='comprado'),atualizadaEm:new Date().toISOString()}:l)}));setView('resumo');setNotice('Compra salva e base de preços atualizada')};

  const comparison=useMemo(()=>{const names=new Set<string>();state.purchases.forEach(p=>p.itens.forEach(i=>{const m=i.mercado||p.mercado;if(m)names.add(m)}));return [...names].map(name=>{let total=0,covered=0;items.forEach(item=>{const prices=hist.get(normalize(item.nome))?.markets.get(name);if(prices?.length){total+=prices.reduce((a,b)=>a+b,0)/prices.length*item.quantidade;covered++}});return{name,total,covered}}).filter(x=>x.covered).sort((a,b)=>b.covered-a.covered||a.total-b.total)},[state.purchases,items,hist]);
  const totalSpent=state.purchases.reduce((s,p)=>s+p.total,0); const avgTicket=state.purchases.length?totalSpent/state.purchases.length:0;
  const likely=pantry.filter(x=>x.ratio>=.8&&!items.some(i=>normalize(i.nome)===normalize(x.name))).slice(0,6);

  const nav:[View,string,string][]=[['inicio','Início','⌂'],['listas','Listas','☷'],['lista','Lista','＋'],['mercado','Comprar','✓'],['precos','Preços','↕']];
  return <div className="min-h-screen bg-slate-50 text-slate-900">
    <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-blue-600 text-xl text-white">🛒</div><div><h1 className="font-bold">Shopping Pro</h1><p className="text-xs text-slate-500">Inteligência de consumo</p></div></div><button onClick={()=>setShowSettings(true)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold">Configurar</button></div></header>
    {notice&&<div className="fixed left-1/2 top-20 z-50 -translate-x-1/2 rounded-2xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white shadow-xl">{notice}</div>}
    <main className="mx-auto max-w-6xl px-4 pb-28 pt-5">
      {view==='inicio'&&<div className="space-y-4"><section className="rounded-3xl bg-gradient-to-br from-blue-700 to-blue-500 p-5 text-white"><p className="text-sm text-blue-100">Próxima compra</p><h2 className="text-2xl font-bold">{list.nome}</h2><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-3"><span className="text-xs text-blue-100">Estimativa</span><strong className="block text-xl">{money(projected)}</strong></div><div className="rounded-2xl bg-white/10 p-3"><span className="text-xs text-blue-100">Orçamento</span><strong className="block text-xl">{money(state.budget||0)}</strong></div></div><button onClick={()=>setShowMarket(true)} className="mt-4 w-full rounded-2xl bg-white py-3 font-bold text-blue-700">Iniciar compra</button></section><div className="grid gap-4 md:grid-cols-3"><Card><div className="flex justify-between"><h3 className="font-bold">Assistente de compra</h3><Pill tone="blue">local</Pill></div><p className="mt-3 text-sm text-slate-600">{likely.length?`${likely.length} produto(s) provavelmente próximos da reposição.`:'Nenhuma reposição urgente pelo histórico atual.'}</p></Card><Card><h3 className="font-bold">Despensa estimada</h3><strong className="mt-2 block text-3xl">{likely.length}</strong><p className="text-sm text-slate-500">provavelmente acabando</p><button onClick={()=>setView('resumo')} className="mt-3 text-sm font-semibold text-blue-700">Ver previsão →</button></Card><Card><h3 className="font-bold">Seu consumo</h3><strong className="mt-2 block text-3xl">{money(avgTicket)}</strong><p className="text-sm text-slate-500">ticket médio</p><button onClick={()=>setView('resumo')} className="mt-3 text-sm font-semibold text-blue-700">Abrir resumo →</button></Card></div><Card><div className="flex justify-between"><div><h3 className="font-bold">Sugestão para a próxima compra</h3><p className="text-sm text-slate-500">Aprendizado pela frequência de consumo.</p></div><Pill tone="green">aprendizado</Pill></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{likely.map(x=><button key={x.name} onClick={()=>addHistory(x)} className="flex items-center justify-between rounded-2xl border border-slate-200 p-3 text-left"><div><strong className="text-sm">{x.name}</strong><p className="text-xs text-slate-500">ciclo ~{x.avgInterval} dias · última há {x.since}</p></div><span className="text-blue-600">＋</span></button>)}</div></Card></div>}

      {view==='listas'&&<section><div className="mb-5 flex justify-between"><div><h2 className="text-2xl font-bold">Minhas listas</h2><p className="text-sm text-slate-500">Separe cada tipo de compra.</p></div><button onClick={()=>setShowList(true)} className="rounded-2xl bg-blue-600 px-4 py-2 font-bold text-white">+ Nova</button></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{state.lists.filter(l=>!l.arquivada).map(l=><button key={l.id} onClick={()=>{setState(s=>({...s,activeListId:l.id}));setView('lista')}} className={`rounded-3xl border p-5 text-left ${l.id===state.activeListId?'border-blue-300 bg-blue-50':'border-slate-200 bg-white'}`}><div className="flex justify-between"><span className="text-2xl">🧾</span><Pill tone={l.id===state.activeListId?'blue':'slate'}>{l.itens.length} itens</Pill></div><h3 className="mt-4 text-lg font-bold">{l.nome}</h3><p className="mt-1 text-sm text-slate-500">{l.descricao||'Sem descrição'}</p></button>)}</div></section>}

      {view==='lista'&&<div className="space-y-4"><section className="rounded-3xl bg-gradient-to-br from-blue-700 to-blue-500 p-5 text-white"><div className="flex justify-between"><div><p className="text-sm text-blue-100">Lista ativa</p><h2 className="text-2xl font-bold">{list.nome}</h2><p className="text-sm text-blue-100">{items.length} itens · {money(projected)}</p></div><button onClick={()=>setShowMarket(true)} className="rounded-xl bg-white px-3 py-2 text-sm font-bold text-blue-700">Comprar</button></div></section><Card><h3 className="font-bold">Adição rápida</h3><p className="mb-3 text-sm text-slate-500">Digite ou reaproveite seu histórico.</p><div className="flex gap-2"><input value={quick} onChange={e=>setQuick(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addQuick()} placeholder="2 leite, arroz 5kg, 3 detergentes" className="min-w-0 flex-1 rounded-2xl border px-4 py-3"/><button onClick={addQuick} className="rounded-2xl bg-blue-600 px-4 font-bold text-white">Adicionar</button></div><div className="mt-4 flex gap-2"><button onClick={()=>setHistoryMode('freq')} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${historyMode==='freq'?'bg-blue-600 text-white':'bg-slate-100'}`}>Mais frequentes</button><button onClick={()=>setHistoryMode('recent')} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${historyMode==='recent'?'bg-blue-600 text-white':'bg-slate-100'}`}>Recentes</button></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{suggestions.map(x=><button key={x.name} onClick={()=>addHistory(x)} className="min-w-[160px] rounded-2xl border p-3 text-left"><strong className="block text-sm">{x.name}</strong><span className="text-xs text-slate-500">{x.count} compra(s) · média {money(x.prices.reduce((a,b)=>a+b,0)/x.prices.length)}</span></button>)}</div></Card><Card><div className="mb-3 flex justify-between"><h3 className="font-bold">Itens</h3><span className="text-sm text-slate-500">{pending.length} pendentes</span></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar item" className="mb-3 w-full rounded-2xl border px-4 py-2.5"/><div className="space-y-2">{items.filter(i=>normalize(i.nome).includes(normalize(search))).map(i=><button key={i.id} onClick={()=>setEditing({...i})} className="flex w-full items-center justify-between rounded-2xl border border-slate-100 p-3 text-left"><div><strong className={i.status==='comprado'?'text-slate-400 line-through':''}>{i.quantidade}x {i.nome}</strong><p className="text-xs text-slate-500">{i.categoria}</p></div><strong>{money((i.precoReal??i.precoEstimado)*i.quantidade)}</strong></button>)}</div></Card></div>}

      {view==='mercado'&&<div className="space-y-3"><Card className="sticky top-20 z-20"><div className="flex justify-between"><div><p className="text-xs text-slate-500">Comprando em</p><h2 className="text-xl font-bold">{state.currentMarket||list.mercado||'Selecione o mercado'}</h2></div><button onClick={()=>setShowMarket(true)} className="rounded-xl border px-3 py-2 text-sm font-semibold">Trocar mercado</button></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600" style={{width:`${progress}%`}}/></div><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{bought.length}/{items.length} itens</span><span>{money(actual)}</span></div></Card>{items.map(i=>{const h=hist.get(normalize(i.nome));const avg=h?.prices.length?h.prices.reduce((a,b)=>a+b,0)/h.prices.length:0;const current=i.precoReal??i.precoEstimado;const high=avg>0&&current>avg*1.1;return <Card key={i.id} className={i.status==='comprado'?'opacity-75':''}><div className="flex gap-3"><button onClick={()=>toggle(i.id)} className={`h-8 w-8 shrink-0 rounded-xl border font-bold ${i.status==='comprado'?'border-blue-600 bg-blue-600 text-white':'border-slate-300'}`}>{i.status==='comprado'?'✓':''}</button><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><div><strong>{i.quantidade}x {i.nome}</strong><p className="text-xs text-slate-500">{i.categoria}{i.mercadoCompra?` · ${i.mercadoCompra}`:''}</p></div>{high&&<Pill tone="red">acima da média</Pill>}</div><div className="mt-3 flex items-center gap-2"><span className="text-sm text-slate-500">Preço unit.</span><input type="number" step="0.01" value={i.precoReal??''} placeholder={i.precoEstimado?String(i.precoEstimado):'0,00'} onChange={e=>updateList(l=>({...l,itens:l.itens.map(x=>x.id===i.id?{...x,precoReal:Number(e.target.value)}:x)}))} className="w-28 rounded-xl border px-3 py-2 text-right font-semibold"/></div>{avg>0&&<p className="mt-2 text-xs text-slate-500">Sua média histórica: {money(avg)}</p>}</div></div></Card>})}<button onClick={finish} className="w-full rounded-2xl bg-blue-600 py-4 font-bold text-white">Finalizar compra · {money(actual)}</button></div>}

      {view==='precos'&&<div className="space-y-4"><div><h2 className="text-2xl font-bold">Inteligência de preços</h2><p className="text-sm text-slate-500">Baseada nas suas compras reais.</p></div><Card><h3 className="font-bold">Comparação da lista atual</h3><div className="mt-3 space-y-2">{comparison.length?comparison.map((m,idx)=><div key={m.name} className="flex justify-between rounded-2xl bg-slate-50 p-3"><div><div className="flex gap-2"><strong>{m.name}</strong>{idx===0&&<Pill tone="green">melhor cobertura</Pill>}</div><p className="text-xs text-slate-500">{m.covered}/{items.length} produtos com histórico</p></div><strong>{money(m.total)}</strong></div>):<p className="text-sm text-slate-500">Finalize mais compras para comparar mercados.</p>}</div></Card><div className="grid gap-3 md:grid-cols-2">{[...hist.values()].sort((a,b)=>b.count-a.count).map(x=>{const avg=x.prices.reduce((a,b)=>a+b,0)/x.prices.length;const min=Math.min(...x.prices);const best=[...x.markets.entries()].map(([m,p])=>[m,p.reduce((a,b)=>a+b,0)/p.length] as const).sort((a,b)=>a[1]-b[1])[0];return <Card key={x.name}><div className="flex justify-between"><div><h3 className="font-bold">{x.name}</h3><p className="text-xs text-slate-500">{x.count} compra(s)</p></div><Pill tone="blue">{x.category}</Pill></div><div className="mt-4 grid grid-cols-3 gap-2 text-sm"><div><span className="text-xs text-slate-500">Média</span><strong className="block">{money(avg)}</strong></div><div><span className="text-xs text-slate-500">Menor</span><strong className="block">{money(min)}</strong></div><div><span className="text-xs text-slate-500">Melhor mercado</span><strong className="block truncate">{best?.[0]||'-'}</strong></div></div></Card>})}</div><button onClick={()=>setView('resumo')} className="w-full rounded-2xl border border-blue-200 bg-blue-50 py-3 font-bold text-blue-700">Ver resumo, despensa e histórico</button></div>}

      {view==='resumo'&&<div className="space-y-4"><div><h2 className="text-2xl font-bold">Resumo e despensa</h2><p className="text-sm text-slate-500">Previsão sem exigir controle manual de estoque.</p></div><div className="grid gap-3 sm:grid-cols-3"><Card><span className="text-sm text-slate-500">Total histórico</span><strong className="block text-2xl">{money(totalSpent)}</strong></Card><Card><span className="text-sm text-slate-500">Ticket médio</span><strong className="block text-2xl">{money(avgTicket)}</strong></Card><Card><span className="text-sm text-slate-500">Compras</span><strong className="block text-2xl">{state.purchases.length}</strong></Card></div><Card><h3 className="font-bold">Despensa estimada</h3><div className="mt-3 space-y-2">{pantry.slice(0,12).map(x=>{const tone=x.ratio>=1?'red':x.ratio>=.8?'amber':'green';const label=x.ratio>=1?'provavelmente acabou':x.ratio>=.8?'provavelmente acabando':'provavelmente ainda possui';return <div key={x.name} className="flex justify-between rounded-2xl bg-slate-50 p-3"><div><strong className="text-sm">{x.name}</strong><p className="text-xs text-slate-500">última há {x.since} dias · ciclo ~{x.avgInterval}</p></div><Pill tone={tone}>{label}</Pill></div>})}</div></Card><Card><h3 className="font-bold">Histórico de compras</h3><div className="mt-3 space-y-2">{state.purchases.map(p=><details key={p.id} className="rounded-2xl border p-3"><summary className="cursor-pointer list-none"><div className="flex justify-between"><div><strong>{p.mercado||p.listaNome}</strong><p className="text-xs text-slate-500">{new Date(p.data).toLocaleDateString('pt-BR')} · {p.itens.length} itens</p></div><strong>{money(p.total)}</strong></div></summary><div className="mt-3 border-t pt-2">{p.itens.map((i,idx)=><div key={idx} className="flex justify-between py-1 text-sm"><span>{i.quantidade}x {i.nome}{i.mercado&&i.mercado!==p.mercado?` · ${i.mercado}`:''}</span><span>{money(i.total)}</span></div>)}</div></details>)}</div></Card></div>}
    </main>

    <nav className="fixed bottom-0 left-0 right-0 z-30 border-t border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto grid max-w-3xl grid-cols-5">{nav.map(([k,l,i])=><button key={k} onClick={()=>setView(k)} className={`flex flex-col items-center gap-1 py-3 text-xs font-semibold ${view===k?'text-blue-700':'text-slate-500'}`}><span className="text-xl">{i}</span>{l}</button>)}</div></nav>

    {showList&&<div className="fixed inset-0 z-50 flex items-end bg-slate-950/35 sm:items-center sm:justify-center"><div className="w-full rounded-t-3xl bg-white p-5 sm:max-w-md sm:rounded-3xl"><h3 className="text-xl font-bold">Nova lista</h3><input autoFocus value={listName} onChange={e=>setListName(e.target.value)} placeholder="Ex.: Compras de setembro" className="mt-4 w-full rounded-2xl border px-4 py-3"/><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setShowList(false)} className="rounded-2xl border py-3 font-semibold">Cancelar</button><button onClick={()=>{const name=listName.trim();if(!name)return;const now=new Date().toISOString();const l:LocalShoppingList={id:createLocalId('lista'),nome:name,criadaEm:now,atualizadaEm:now,arquivada:false,itens:[]};setState(s=>({...s,activeListId:l.id,lists:[l,...s.lists]}));setListName('');setShowList(false);setView('lista')}} className="rounded-2xl bg-blue-600 py-3 font-bold text-white">Criar</button></div></div></div>}

    {showMarket&&<div className="fixed inset-0 z-50 flex items-end bg-slate-950/35 sm:items-center sm:justify-center"><div className="w-full rounded-t-3xl bg-white p-5 sm:max-w-md sm:rounded-3xl"><h3 className="text-xl font-bold">Onde você está comprando?</h3><p className="mt-1 text-sm text-slate-500">O mercado escolhido será aplicado aos próximos itens e pode ser trocado durante a compra.</p><div className="mt-4 grid grid-cols-2 gap-2">{state.markets.map(m=><button key={m.id} onClick={()=>chooseMarket(m.nome)} className={`rounded-2xl border p-4 text-left font-semibold ${state.currentMarket===m.nome?'border-blue-400 bg-blue-50 text-blue-700':'border-slate-200'}`}>{m.nome}</button>)}</div><button onClick={()=>setShowMarket(false)} className="mt-4 w-full rounded-2xl border py-3 font-semibold">Cancelar</button></div></div>}

    {editing&&<div className="fixed inset-0 z-50 flex items-end bg-slate-950/35 sm:items-center sm:justify-center"><div className="w-full rounded-t-3xl bg-white p-5 sm:max-w-lg sm:rounded-3xl"><div className="flex justify-between"><h3 className="text-xl font-bold">Editar item</h3><button onClick={()=>setEditing(null)}>✕</button></div><div className="mt-4 grid gap-3"><input value={editing.nome} onChange={e=>setEditing({...editing,nome:e.target.value})} className="rounded-2xl border px-4 py-3"/><div className="grid grid-cols-2 gap-2"><input type="number" min="1" value={editing.quantidade} onChange={e=>setEditing({...editing,quantidade:Number(e.target.value)})} className="rounded-2xl border px-4 py-3"/><input type="number" step="0.01" value={editing.precoEstimado} onChange={e=>setEditing({...editing,precoEstimado:Number(e.target.value)})} className="rounded-2xl border px-4 py-3"/></div><select value={editing.categoria} onChange={e=>setEditing({...editing,categoria:e.target.value})} className="rounded-2xl border px-4 py-3">{state.categories.map(c=><option key={c}>{c}</option>)}</select><input value={editing.ean||''} onChange={e=>setEditing({...editing,ean:e.target.value})} placeholder="EAN / código de barras (opcional)" className="rounded-2xl border px-4 py-3"/></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>{updateList(l=>({...l,itens:l.itens.filter(i=>i.id!==editing.id)}));setEditing(null)}} className="rounded-2xl border border-red-200 py-3 font-semibold text-red-600">Remover</button><button onClick={()=>{updateList(l=>({...l,itens:l.itens.map(i=>i.id===editing.id?editing:i)}));setEditing(null);setNotice('Item atualizado')}} className="rounded-2xl bg-blue-600 py-3 font-bold text-white">Salvar</button></div></div></div>}

    {showSettings&&<div className="fixed inset-0 z-50 flex items-end bg-slate-950/35 sm:items-center sm:justify-center"><div className="max-h-[88vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 sm:max-w-lg sm:rounded-3xl"><div className="flex justify-between"><div><h3 className="text-xl font-bold">Configurações</h3><p className="text-sm text-slate-500">Categorias, mercados e orçamento.</p></div><button onClick={()=>setShowSettings(false)}>✕</button></div><label className="mt-5 block text-sm font-semibold">Orçamento</label><input type="number" value={state.budget||''} onChange={e=>setState(s=>({...s,budget:Number(e.target.value)}))} className="mt-2 w-full rounded-2xl border px-4 py-3"/><div className="mt-5"><h4 className="font-bold">Categorias</h4><div className="mt-2 flex flex-wrap gap-2">{state.categories.map(c=><span key={c} className="flex items-center gap-2 rounded-full bg-slate-100 px-3 py-2 text-sm">{c}<button onClick={()=>state.categories.length>1&&setState(s=>({...s,categories:s.categories.filter(x=>x!==c)}))}>×</button></span>)}</div><div className="mt-3 flex gap-2"><input value={newCategory} onChange={e=>setNewCategory(e.target.value)} placeholder="Nova categoria" className="min-w-0 flex-1 rounded-2xl border px-4 py-3"/><button onClick={()=>{const c=newCategory.trim();if(c&&!state.categories.some(x=>normalize(x)===normalize(c))){setState(s=>({...s,categories:[...s.categories,c]}));setNewCategory('')}}} className="rounded-2xl bg-blue-600 px-4 font-bold text-white">Adicionar</button></div></div><div className="mt-5"><h4 className="font-bold">Meus mercados</h4><div className="mt-2 space-y-2">{state.markets.map(m=><div key={m.id} className="flex justify-between rounded-2xl bg-slate-50 px-3 py-2"><span>{m.nome}</span><button onClick={()=>setState(s=>({...s,markets:s.markets.filter(x=>x.id!==m.id)}))} className="text-sm text-red-500">Remover</button></div>)}</div><div className="mt-3 flex gap-2"><input value={newMarket} onChange={e=>setNewMarket(e.target.value)} placeholder="Novo mercado" className="min-w-0 flex-1 rounded-2xl border px-4 py-3"/><button onClick={()=>{const n=newMarket.trim();if(n&&!state.markets.some(x=>normalize(x.nome)===normalize(n))){const m:LocalMarket={id:createLocalId('mercado'),nome:n};setState(s=>({...s,markets:[...s.markets,m]}));setNewMarket('')}}} className="rounded-2xl bg-blue-600 px-4 font-bold text-white">Adicionar</button></div></div><button onClick={()=>{if(confirm('Restaurar dados de demonstração?'))setState(resetLocalShoppingState())}} className="mt-6 w-full rounded-2xl border border-red-200 py-3 font-semibold text-red-600">Restaurar demonstração</button></div></div>}
  </div>;
}
