import { Card, EmptyState, Pill } from '../../components/ui';
import { money, normalize } from '../../services/shoppingIntelligence';
import type { AppData, PantryPrediction } from '../../types/domain';

export function InsightsPage({ data, pantry }: { data: AppData; pantry: PantryPrediction[] }) {
  if (!data.purchases.length) return <EmptyState title="Resumo em preparação" description="Depois da primeira compra, você verá gastos, recorrência, despensa estimada e evolução dos preços."/>;
  const total = data.purchases.reduce((s, p) => s + Number(p.total_price), 0); const sessions = new Set(data.purchases.map(p => p.shopping_session_id)).size;
  const marketSpend = new Map<string, number>(); const productCounts = new Map<string, number>();
  data.purchases.forEach(p => { marketSpend.set(p.market_id, (marketSpend.get(p.market_id) || 0) + Number(p.total_price)); const key = normalize(p.product_name_snapshot); productCounts.set(key, (productCounts.get(key) || 0) + Number(p.quantity)); });
  const usedMarket = [...marketSpend].sort((a, b) => b[1] - a[1])[0]; const marketName = data.markets.find(m => m.id === usedMarket?.[0])?.name || 'Não informado';
  const mostBought = [...productCounts].sort((a, b) => b[1] - a[1])[0]; const mostBoughtName = data.purchases.find(p => normalize(p.product_name_snapshot) === mostBought?.[0])?.product_name_snapshot || '-';
  return <div className="space-y-4"><div><h2 className="text-2xl font-bold">Resumo e despensa</h2><p className="text-sm text-slate-500">Previsões calculadas sem exigir estoque doméstico rígido.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card><p className="text-sm text-slate-500">Total histórico</p><strong className="block text-2xl">{money(total)}</strong></Card><Card><p className="text-sm text-slate-500">Ticket médio</p><strong className="block text-2xl">{money(total / sessions)}</strong></Card><Card><p className="text-sm text-slate-500">Mercado mais usado</p><strong className="block text-xl">{marketName}</strong></Card><Card><p className="text-sm text-slate-500">Produto mais comprado</p><strong className="block text-xl">{mostBoughtName}</strong></Card></div><Card><h3 className="font-bold">Despensa estimada</h3><div className="mt-3 space-y-2">{pantry.slice(0, 14).map(item => { const tone = item.ratio >= 1 ? 'danger' : item.ratio >= .8 ? 'warning' : 'success'; const label = item.ratio >= 1 ? 'provavelmente acabou' : item.ratio >= .8 ? 'provavelmente acabando' : 'provavelmente ainda possui'; return <div key={item.name} className="flex items-center justify-between gap-3 rounded-2xl bg-slate-50 p-3"><div><strong className="text-sm">{item.name}</strong><p className="text-xs text-slate-500">Última há {item.daysSinceLastPurchase} dias, ciclo médio {item.averageIntervalDays}</p></div><Pill tone={tone}>{label}</Pill></div>; })}</div></Card><Card><h3 className="font-bold">Histórico de compras</h3><div className="mt-3 space-y-2">{data.sessions.filter(s => s.status === 'completed').map(session => { const purchases = data.purchases.filter(p => p.shopping_session_id === session.id); const firstMarket = data.markets.find(m => m.id === session.initial_market_id)?.name || 'Compra'; return <details key={session.id} className="rounded-2xl border p-3"><summary className="cursor-pointer list-none"><div className="flex justify-between"><div><strong>{firstMarket}</strong><p className="text-xs text-slate-500">{new Date(session.started_at).toLocaleDateString('pt-BR')} · {purchases.length} itens</p></div><strong>{money(Number(session.total || 0))}</strong></div></summary><div className="mt-3 border-t pt-2">{purchases.map(p => <div key={p.id} className="flex justify-between py-1 text-sm"><span>{p.quantity}x {p.product_name_snapshot}</span><span>{money(Number(p.total_price))}</span></div>)}</div></details>; })}</div></Card></div>;
}

