import { useEffect, useMemo, useState } from 'react';
import type { Session, User } from '@supabase/supabase-js';
import { BarChart3, Download, Home, ListChecks, LogOut, Settings, Share, ShoppingCart, SquarePlus, Tags, X } from 'lucide-react';
import { supabase, hasSupabaseConfig } from '../lib/supabase';
import { AuthPage } from '../features/auth/AuthPage';
import { useShoppingData } from '../hooks/useShoppingData';
import { useInstallPrompt } from '../hooks/useInstallPrompt';
import { Dashboard } from '../features/dashboard/Dashboard';
import { ListsPage } from '../features/shopping-lists/ListsPage';
import { ShoppingMode } from '../features/shopping-mode/ShoppingMode';
import { PricesPage } from '../features/prices/PricesPage';
import { InsightsPage } from '../features/insights/InsightsPage';
import { SettingsDrawer } from '../features/settings/SettingsDrawer';
import { ErrorState, LoadingState } from '../components/ui';
import { pantryPredictions, priceHistory } from '../services/shoppingIntelligence';

type View = 'home' | 'lists' | 'shopping' | 'prices' | 'insights';
export default function App() {
  const [session, setSession] = useState<Session | null>(null); const [authLoading, setAuthLoading] = useState(true); const [view, setView] = useState<View>('home'); const [activeListId, setActiveListId] = useState(''); const [notice, setNotice] = useState(''); const [settings, setSettings] = useState(false); const [installHelp, setInstallHelp] = useState(false);
  const user: User | null = session?.user || null; const { data, loading, error, reload } = useShoppingData(user);
  const install = useInstallPrompt();
  const handleInstallClick = () => {
    if (install.installed) return setNotice('7Mercado já está instalado nesse dispositivo');
    if (install.canInstall) return void install.promptInstall();
    if (install.ios) return setInstallHelp(true);
    setNotice('Seu navegador não permite instalar por aqui. Tente pelo Chrome ou Safari.');
  };
  useEffect(() => { void supabase.auth.getSession().then(({ data: result }) => { setSession(result.session); setAuthLoading(false); }); const { data: listener } = supabase.auth.onAuthStateChange((_event, current) => { setSession(current); setAuthLoading(false); }); return () => listener.subscription.unsubscribe(); }, []);
  useEffect(() => { if (!activeListId && data.lists[0]) setActiveListId(data.lists[0].id); }, [data.lists, activeListId]);
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(''), 3000); return () => window.clearTimeout(timer); }, [notice]);
  const activeList = data.lists.find(list => list.id === activeListId) || data.lists[0]; const history = useMemo(() => priceHistory(data.purchases, data.markets), [data.purchases, data.markets]); const pantry = useMemo(() => pantryPredictions(history, data.purchases), [history, data.purchases]);
  if (!hasSupabaseConfig) return <main className="grid min-h-screen place-items-center bg-slate-50 p-5 dark:bg-slate-900"><div className="max-w-lg rounded-3xl border bg-white p-6 text-center dark:border-slate-700 dark:bg-slate-800"><h1 className="text-xl font-bold dark:text-slate-100">Configuração pendente</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Defina VITE_SUPABASE_URL e VITE_SUPABASE_KEY no ambiente da branch develop.</p></div></main>;
  if (authLoading) return <LoadingState/>; if (!user) return <AuthPage/>;
  const nav: Array<[View, string, typeof Home]> = [['home', 'Início', Home], ['lists', 'Listas', ListChecks], ['shopping', 'Comprar', ShoppingCart], ['prices', 'Preços', Tags], ['insights', 'Resumo', BarChart3]];
  return <div className="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-900 dark:text-slate-100"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur dark:border-slate-700 dark:bg-slate-900/90" style={{ paddingTop: 'env(safe-area-inset-top)' }}><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3"><div className="flex items-center gap-3"><button onClick={handleInstallClick} className="relative grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-2xl border border-brand-100 bg-white shadow-sm" aria-label="Instalar o 7Mercado no celular"><img src="/icons/icon-192-v3.png" alt="7Mercado" className="h-full w-full object-cover"/>{!install.installed && <span className="absolute -bottom-1 -right-1 grid h-5 w-5 place-items-center rounded-full border-2 border-white bg-brand-500 text-white dark:border-slate-900"><Download size={11}/></span>}</button><div><div className="flex items-center gap-2"><h1 className="font-bold">7Mercado</h1><span className="hidden text-xs text-slate-400 sm:inline dark:text-slate-500">Consult Services</span></div><p className="text-xs text-slate-500 dark:text-slate-400">{view === 'home' ? 'Visão geral' : view === 'lists' ? 'Planejamento' : view === 'shopping' ? 'Modo mercado' : view === 'prices' ? 'Inteligência de preços' : 'Resumo e despensa'}</p></div></div><div className="flex items-center gap-1"><button onClick={() => setSettings(true)} className="rounded-xl p-2.5 text-slate-600 dark:text-slate-400" aria-label="Configurações"><Settings size={19}/></button><button onClick={() => void supabase.auth.signOut()} className="rounded-xl p-2.5 text-slate-600 dark:text-slate-400" aria-label="Sair"><LogOut size={19}/></button></div></div></header>
    {notice && <div className="fixed left-1/2 top-20 z-[60] -translate-x-1/2 whitespace-nowrap rounded-2xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white shadow-xl">{notice}</div>}
    <main className="mx-auto max-w-6xl px-4 pt-5" style={{ paddingBottom: 'calc(7rem + env(safe-area-inset-bottom))' }}>{loading ? <LoadingState/> : error ? <ErrorState message={error} retry={() => void reload()}/> : <>{view === 'home' && <Dashboard data={data} activeList={activeList} history={history} pantry={pantry} openList={() => setView('lists')} startShopping={() => setView('shopping')} openInsights={() => setView('insights')}/>} {view === 'lists' && <ListsPage userId={user.id} data={data} activeList={activeList} selectList={setActiveListId} reload={reload} startShopping={() => setView('shopping')} notify={setNotice}/>} {view === 'shopping' && <ShoppingMode userId={user.id} data={data} list={activeList} history={history} reload={reload} notify={setNotice} done={() => setView('insights')}/>} {view === 'prices' && <PricesPage data={data} history={history} list={activeList}/>} {view === 'insights' && <InsightsPage data={data} pantry={pantry}/>}</>}</main>
    <nav className="fixed bottom-0 left-0 right-0 z-30 border-t border-slate-200 bg-white/95 backdrop-blur dark:border-slate-700 dark:bg-slate-900/90" style={{ paddingBottom: 'env(safe-area-inset-bottom)' }}><div className="mx-auto grid max-w-3xl grid-cols-5">{nav.map(([key, label, Icon]) => <button key={key} onClick={() => setView(key)} className={`flex min-h-[3rem] flex-col items-center justify-center gap-1 py-3 text-xs font-semibold ${view === key ? 'text-brand-700 dark:text-brand-400' : 'text-slate-500 dark:text-slate-400'}`}><Icon size={21}/>{label}</button>)}</div></nav>
    {settings && <SettingsDrawer userId={user.id} data={data} close={() => setSettings(false)} reload={reload} notify={setNotice}/>}
    {installHelp && <div onClick={() => setInstallHelp(false)} className="fixed inset-0 z-50 flex items-end bg-slate-950/40 sm:items-center sm:justify-center"><div onClick={e => e.stopPropagation()} className="w-full rounded-t-3xl bg-white p-5 dark:bg-slate-800 sm:max-w-md sm:rounded-3xl"><div className="flex items-start justify-between"><h3 className="text-xl font-bold">Instalar o 7Mercado</h3><button onClick={() => setInstallHelp(false)} aria-label="Fechar" className="rounded-xl p-1 text-slate-500 dark:text-slate-400"><X size={20}/></button></div><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">No iPhone/iPad, a Apple exige que a instalação seja feita manualmente pelo Safari:</p><ol className="mt-4 space-y-3 text-sm"><li className="flex items-start gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-brand-50 font-bold text-brand-700 dark:bg-brand-500/15 dark:text-brand-300">1</span><span className="pt-0.5">Toque no ícone de compartilhar <Share size={14} className="inline align-text-bottom"/> na barra do Safari</span></li><li className="flex items-start gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-brand-50 font-bold text-brand-700 dark:bg-brand-500/15 dark:text-brand-300">2</span><span className="pt-0.5">Escolha “Adicionar à Tela de Início” <SquarePlus size={14} className="inline align-text-bottom"/></span></li><li className="flex items-start gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-brand-50 font-bold text-brand-700 dark:bg-brand-500/15 dark:text-brand-300">3</span><span className="pt-0.5">Toque em “Adicionar” — o 7Mercado aparece na tela inicial como um app</span></li></ol><button onClick={() => setInstallHelp(false)} className="mt-5 w-full rounded-2xl bg-brand-600 py-3 font-bold text-white">Entendi</button></div></div>}
  </div>;
}

