import { useState } from 'react';
import type { AppData } from '../../types/domain';
import { shoppingRepository } from '../../repositories/shoppingRepository';
import { friendlyError } from '../../lib/errors';

export function SettingsDrawer({ userId, data, close, reload, notify }: { userId: string; data: AppData; close: () => void; reload: () => Promise<void>; notify: (text: string) => void }) {
  const [category, setCategory] = useState(''); const [market, setMarket] = useState('');
  const run = async (action: () => Promise<unknown>) => { try { await action(); await reload(); } catch (e) { notify(friendlyError(e)); } };
  return <div className="fixed inset-0 z-50 flex items-end bg-slate-950/40 sm:items-center sm:justify-center"><div className="max-h-[90vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 sm:max-w-lg sm:rounded-3xl"><div className="flex justify-between"><div><h3 className="text-xl font-bold">Configurações</h3><p className="text-sm text-slate-500">Categorias e mercados da sua conta.</p></div><button onClick={close} aria-label="Fechar" className="rounded-xl px-3 py-2">✕</button></div><section className="mt-5"><h4 className="font-bold">Categorias</h4><div className="mt-2 flex flex-wrap gap-2">{data.categories.map(c => <span key={c.id} className="flex items-center gap-2 rounded-full bg-slate-100 px-3 py-2 text-sm">{c.name}{!c.is_system && <button onClick={() => void run(() => shoppingRepository.removeCategory(c.id))} className="text-danger-500">×</button>}</span>)}</div><div className="mt-3 flex gap-2"><input value={category} onChange={e => setCategory(e.target.value)} className="min-w-0 flex-1 rounded-2xl border px-4 py-3" placeholder="Nova categoria"/><button onClick={() => { const name = category.trim(); if (name) void run(async () => { await shoppingRepository.addCategory(userId, name); setCategory(''); }); }} className="rounded-2xl bg-brand-600 px-4 font-bold text-white">Adicionar</button></div></section><section className="mt-6"><h4 className="font-bold">Mercados</h4><div className="mt-2 space-y-2">{data.markets.map(m => <div key={m.id} className="flex justify-between rounded-2xl bg-slate-50 px-3 py-2"><span>{m.name}</span><button onClick={() => void run(() => shoppingRepository.removeMarket(m.id))} className="text-sm text-danger-500">Remover</button></div>)}</div><div className="mt-3 flex gap-2"><input value={market} onChange={e => setMarket(e.target.value)} className="min-w-0 flex-1 rounded-2xl border px-4 py-3" placeholder="Novo mercado"/><button onClick={() => { const name = market.trim(); if (name) void run(async () => { await shoppingRepository.addMarket(userId, name); setMarket(''); }); }} className="rounded-2xl bg-brand-600 px-4 font-bold text-white">Adicionar</button></div></section></div></div>;
}

