import { useMemo, useState } from 'react';
import type { AppData, ShoppingList } from '../../types/domain';
import { shoppingRepository } from '../../repositories/shoppingRepository';
import { friendlyError } from '../../lib/errors';
import { parseNaturalItems } from '../../services/shoppingIntelligence';
import { Card, EmptyState, Pill } from '../../components/ui';

export function ListsPage({ userId, data, activeList, selectList, reload, startShopping, notify }: { userId: string; data: AppData; activeList?: ShoppingList; selectList: (id: string) => void; reload: () => Promise<void>; startShopping: () => void; notify: (text: string) => void }) {
  const [showNew, setShowNew] = useState(false); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [budget, setBudget] = useState(''); const [quick, setQuick] = useState(''); const [busy, setBusy] = useState(false);
  const items = useMemo(() => data.items.filter(i => i.list_id === activeList?.id && i.status !== 'removed'), [data.items, activeList]);
  const createList = async () => { if (!name.trim()) return; try { setBusy(true); const list = await shoppingRepository.createList(userId, { name: name.trim(), description: description.trim() || null, budget: budget ? Number(budget) : null }); await reload(); selectList(list.id); setShowNew(false); setName(''); notify('Lista criada'); } catch (e) { notify(friendlyError(e)); } finally { setBusy(false); } };
  const addQuick = async () => { const parsed = parseNaturalItems(quick); if (!activeList || !parsed.length) return; try { setBusy(true); await shoppingRepository.addItems(userId, activeList.id, parsed.map(item => ({ name_snapshot: item.name, quantity: item.quantity, category_id: null, estimated_price: null, product_id: null }))); setQuick(''); await reload(); notify(`${parsed.length} item(ns) adicionado(s)`); } catch (e) { notify(friendlyError(e)); } finally { setBusy(false); } };
  const remove = async (id: string) => { try { await shoppingRepository.removeItem(id); await reload(); } catch (e) { notify(friendlyError(e)); } };
  return <div className="space-y-4"><div className="flex items-start justify-between"><div><h2 className="text-2xl font-bold">Minhas listas</h2><p className="text-sm text-slate-500">Planeje diferentes tipos de compra.</p></div><button onClick={() => setShowNew(true)} className="rounded-2xl bg-blue-600 px-4 py-2.5 font-bold text-white">+ Nova</button></div>
    {data.lists.length ? <div className="flex gap-2 overflow-x-auto pb-1">{data.lists.map(list => <button key={list.id} onClick={() => selectList(list.id)} className={`min-w-[190px] rounded-2xl border p-3 text-left ${activeList?.id === list.id ? 'border-blue-400 bg-blue-50' : 'bg-white'}`}><div className="flex justify-between"><strong>{list.name}</strong><Pill tone={activeList?.id === list.id ? 'blue' : 'slate'}>{data.items.filter(i => i.list_id === list.id && i.status === 'pending').length}</Pill></div><p className="mt-1 truncate text-xs text-slate-500">{list.description || 'Sem descrição'}</p></button>)}</div> : <EmptyState title="Nenhuma lista criada" description="Crie uma lista para começar a planejar."/>}
    {activeList && <><Card><div className="flex items-center justify-between"><div><p className="text-xs text-slate-500">Lista ativa</p><h3 className="text-xl font-bold">{activeList.name}</h3></div><button onClick={startShopping} disabled={!items.some(i => i.status === 'pending')} className="rounded-2xl bg-blue-600 px-4 py-2.5 font-bold text-white disabled:opacity-40">Comprar</button></div></Card><Card><h3 className="font-bold">Adição rápida</h3><p className="mb-3 text-sm text-slate-500">Ex.: 2 leite, arroz 5kg, 3 detergentes</p><div className="flex gap-2"><input value={quick} onChange={e => setQuick(e.target.value)} onKeyDown={e => e.key === 'Enter' && void addQuick()} className="min-w-0 flex-1 rounded-2xl border px-4 py-3" placeholder="Digite os produtos"/><button disabled={busy} onClick={() => void addQuick()} className="rounded-2xl bg-blue-600 px-4 font-bold text-white">Adicionar</button></div></Card><Card><div className="mb-3 flex justify-between"><h3 className="font-bold">Itens</h3><span className="text-sm text-slate-500">{items.filter(i => i.status === 'pending').length} pendentes</span></div><div className="space-y-2">{items.length ? items.map(item => <div key={item.id} className="flex items-center justify-between rounded-2xl border border-slate-100 p-3"><div><strong className={item.status === 'purchased' ? 'text-slate-400 line-through' : ''}>{item.quantity}x {item.name_snapshot}</strong><p className="text-xs text-slate-500">{item.estimated_price ? `Estimado em R$ ${Number(item.estimated_price).toFixed(2)}` : 'Sem referência de preço'}</p></div>{item.status === 'pending' && <button onClick={() => void remove(item.id)} className="rounded-xl px-3 py-2 text-sm font-semibold text-red-600">Remover</button>}</div>) : <p className="py-6 text-center text-sm text-slate-500">Adicione o primeiro item acima.</p>}</div></Card></>}
    {showNew && <div className="fixed inset-0 z-50 flex items-end bg-slate-950/40 sm:items-center sm:justify-center"><div className="w-full rounded-t-3xl bg-white p-5 sm:max-w-md sm:rounded-3xl"><h3 className="text-xl font-bold">Nova lista</h3><div className="mt-4 space-y-3"><input autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="Ex.: Compra do mês" className="w-full rounded-2xl border px-4 py-3"/><input value={description} onChange={e => setDescription(e.target.value)} placeholder="Descrição opcional" className="w-full rounded-2xl border px-4 py-3"/><input type="number" value={budget} onChange={e => setBudget(e.target.value)} placeholder="Orçamento opcional" className="w-full rounded-2xl border px-4 py-3"/></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={() => setShowNew(false)} className="rounded-2xl border py-3 font-semibold">Cancelar</button><button disabled={busy} onClick={() => void createList()} className="rounded-2xl bg-blue-600 py-3 font-bold text-white">Criar</button></div></div></div>}
  </div>;
}

